import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Next App"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-2 bg-sky-950">Header</header>
        {children}
        <footer className="p-2 bg-sky-950">Footer</footer>
      </body>
    </html>
  );
}
